source 'https://rubygems.org'
gem 'jekyll-twitter-plugin'
gem 'jekyll-email-protect'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'kramdown'
gem 'rouge'
gem 'jekyll-watch'
gem 'jekyll-redirect-from'
gem 'jekyll-feed'
gem 'jemoji'
gem 'git'
gem 'json', "=2.0.2"
